import Head from 'next/head';
import NavbarApp from '@/components/NavbarHome';
import { Loading } from '@nextui-org/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Obstilidraw</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarApp />
      <main>
        <Loading color="primary">This is the index, WIP</Loading>
      </main>
    </>
  );
}
