import Head from 'next/head';
import Draw from '@/components/Draw';
import NavbarApp from '@/components/NavbarApp';
import { getProviders } from 'next-auth/react';
import { unstable_getServerSession } from 'next-auth/next';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default function Edit({ providers, data }: any) {
  return (
    <>
      <Head>
        <title>Obstilidraw</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarApp providers={providers} />
      <main>
        <Draw initialData={data} />
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const { id } = context.query;
  const providers = await getProviders();
  const session = await unstable_getServerSession(context.req, context.res, authOptions);
  let data;

  if (!session) {
    return {
      props: {
        providers,
        data: null
      }
    };
  }

  data = await prisma.draw.findFirst({
    where: {
      id: Number(id[0]),
      author: {
        has: session?.user?.email
      }
    }
  });

  if (!data) {
    return {
      props: {
        providers,
        data: null
      }
    };
  }

  data = {
    elements: JSON.parse(data!.element),
    appState: JSON.parse(data!.state),
    files: JSON.parse(data!.file)
  };

  return {
    props: {
      providers,
      data
    }
  };
}
